using Newtonsoft.Json.Linq;
using System.Runtime.Serialization;

namespace ApiAggregation.Models.Enums
{
    public enum NewsApiCountryEnumOption
    {
        [EnumMember(Value = "ae")] ae,
        [EnumMember(Value = "ar")] ar,
        [EnumMember(Value = "at")] at,
        [EnumMember(Value = "au")] au,
        [EnumMember(Value = "be")] be,
        [EnumMember(Value = "bg")] bg,
        [EnumMember(Value = "br")] br,
        [EnumMember(Value = "ca")] ca,
        [EnumMember(Value = "ch")] ch,
        [EnumMember(Value = "cn")] cn,
        [EnumMember(Value = "co")] co,
        [EnumMember(Value = "cu")] cu,
        [EnumMember(Value = "cz")] cz,
        [EnumMember(Value = "de")] de,
        [EnumMember(Value = "eg")] eg,
        [EnumMember(Value = "fr")] fr,
        [EnumMember(Value = "gb")] gb,
        [EnumMember(Value = "gr")] gr,
        [EnumMember(Value = "hk")] hk,
        [EnumMember(Value = "hu")] hu,
        [EnumMember(Value = "id")] id,
        [EnumMember(Value = "ie")] ie,
        [EnumMember(Value = "il")] il,
        [EnumMember(Value = "it")] it,
        [EnumMember(Value = "jp")] jp,
        [EnumMember(Value = "kr")] kr,
        [EnumMember(Value = "lt")] lt,
        [EnumMember(Value = "lv")] lv,
        [EnumMember(Value = "ma")] ma,
        [EnumMember(Value = "mx")] mx,
        [EnumMember(Value = "my")] my,
        [EnumMember(Value = "ng")] ng,
        [EnumMember(Value = "nl")] nl,
        [EnumMember(Value = "no")] no,
        [EnumMember(Value = "nz")] nz,
        [EnumMember(Value = "ph")] ph,
        [EnumMember(Value = "pl")] pl,
        [EnumMember(Value = "pt")] pt,
        [EnumMember(Value = "ro")] ro,
        [EnumMember(Value = "rs")] rs,
        [EnumMember(Value = "ru")] ru,
        [EnumMember(Value = "sa")] sa,
        [EnumMember(Value = "se")] se,
        [EnumMember(Value = "sg")] sg,
        [EnumMember(Value = "si")] si,
        [EnumMember(Value = "sk")] sk,
        [EnumMember(Value = "th")] th,
        [EnumMember(Value = "tr")] tr,
        [EnumMember(Value = "tw")] tw,
        [EnumMember(Value = "ua")] ua,
        [EnumMember(Value = "us")] us,
        [EnumMember(Value = "ve")] ve,
        [EnumMember(Value = "za")] za
    }
}
